import type { CanonicalInbound, Intent } from '@mango/contracts';
import { copy } from '@mango/seed-data';
import { classify, formatRecommendation, HermesAgentClient, rankOpportunities, safeName } from './conversation.js';
import type { MangoDb, SessionRow, UserRow } from './db.js';
import { signAppToken } from './token.js';

export interface OrchestratorOptions { maxTurns:number; warningAt:number; appBaseUrl:string; linkSecret:string; }
interface AcceptedInbound { messageId:string; userId:string; sessionId:string; isNew:boolean; }
export class Orchestrator {
  readonly hermes:HermesAgentClient;
  constructor(private readonly db:MangoDb,private readonly opts:OrchestratorOptions={maxTurns:Number(process.env.MAX_USER_TURNS||12),warningAt:Number(process.env.TURN_WARNING_AT||10),appBaseUrl:process.env.APP_DEEP_LINK_BASE_URL||'http://localhost:3000',linkSecret:process.env.DEEP_LINK_SIGNING_SECRET||'demo-deep-link-secret'}) { this.hermes=new HermesAgentClient(db); }
  appLink(userId:string,sessionId:string,path='/for-you') { const token=signAppToken(userId,sessionId,this.opts.linkSecret); return `${this.opts.appBaseUrl}${path}${path.includes('?')?'&':'?'}token=${encodeURIComponent(token)}`; }
  private reply(user:UserRow,session:SessionRow,inboundId:string,text:string,kind:string) { let body=text; if(kind!=='warning' && session.inbound_turns===this.opts.warningAt && !session.warning_sent_at){ body=`${body} ${copy.warning}`; this.db.updateSession(session.id,{warning_sent_at:new Date().toISOString()}); } const safe=body.slice(0,600); this.db.insertOutboundMessage(`out:${inboundId}:${kind}`,session.id,safe); this.db.enqueue(user.id,session.id,safe,`reply:${inboundId}:${kind}`); return safe; }
  async enqueue(input:CanonicalInbound) { const text=input.text?.trim()||''; if(!text||text.length>1000) return {accepted:false,reason:'invalid_text'}; const existing=this.db.getUserByPhone(input.from); const user=this.db.getOrCreateUser(input.from); const session=this.db.activeSession(user.id); const inserted=this.db.insertInbound(input.provider_message_id,session.id,text); if(inserted.duplicate) return {accepted:true,duplicate:true,userId:user.id,sessionId:session.id}; const job=this.db.enqueueInbound(input.provider_message_id,inserted.id,user.id,session.id,{...input,text}); return {accepted:true,duplicate:false,queued:true,jobId:job.id,userId:user.id,sessionId:session.id}; }
  async drain(max=100) { let processed=0; while(processed<max){ const job=this.db.claimInbound(); if(!job) break; try { await this.process(JSON.parse(job.payload_json) as CanonicalInbound,{messageId:job.message_id,userId:job.user_id,sessionId:job.session_id,isNew:job.sequence===1 && !(this.db.getUser(job.user_id)?.display_name)}); this.db.completeInbound(job.id); } catch(e:any) { this.db.completeInbound(job.id,e?.message||'processing_error'); } processed++; } return processed; }
  async process(input:CanonicalInbound, accepted?:AcceptedInbound) { const text=input.text?.trim()||''; if(!text||text.length>1000) return {accepted:false,reason:'invalid_text'}; const existing=this.db.getUserByPhone(input.from); const user=accepted?.userId?this.db.getUser(accepted.userId)!:this.db.getOrCreateUser(input.from); let session=accepted?.sessionId?this.db.getSession(accepted.sessionId)!:this.db.activeSession(user.id); const inserted=accepted?{id:accepted.messageId,duplicate:false}:this.db.insertInbound(input.provider_message_id,session.id,text); if(inserted.duplicate) return {accepted:true,duplicate:true,userId:user.id,sessionId:session.id};
    const isNew=accepted?.isNew??!existing; if(isNew) { const first=classify(text,'new',false); if(first.intent==='COMMAND_STOP'){this.db.setMessageIntent(inserted.id,first.intent,'normal');this.db.setUserStatus(user.id,'opted_out');this.reply(user,session,inserted.id,copy.stop,'stop');return {accepted:true,duplicate:false,userId:user.id,sessionId:session.id};} if(first.safety==='high_risk'){this.db.setMessageIntent(inserted.id,first.intent,first.safety);this.reply(user,session,inserted.id,copy.safety,'safety');return {accepted:true,duplicate:false,userId:user.id,sessionId:session.id};} this.db.updateSession(session.id,{state:'awaiting_name',pending_action_json:JSON.stringify({deferred_user_text:text}),last_activity_at:new Date().toISOString(),inbound_turns:0}); this.db.setMessageIntent(inserted.id,'GREETING_OR_SMALLTALK','normal'); if(user.status==='active') this.reply(user,session,inserted.id,copy.firstGreeting,'first'); return {accepted:true,duplicate:false,userId:user.id,sessionId:session.id}; }
    if(user.status==='opted_out' && !/^start$/i.test(text)) return {accepted:true,duplicate:false,userId:user.id,sessionId:session.id};
    const c=classify(text,session.state,!!user.display_name); this.db.setMessageIntent(inserted.id,c.intent,c.safety);
    if(c.intent==='COMMAND_STOP'){ this.db.setUserStatus(user.id,'opted_out'); this.reply(user,session,inserted.id,copy.stop,'stop'); return {accepted:true,userId:user.id,sessionId:session.id}; }
    if(c.intent==='COMMAND_START'){ this.db.setUserStatus(user.id,'active'); this.reply(user,session,inserted.id,copy.start,'start'); return {accepted:true,userId:user.id,sessionId:session.id}; }
    if(c.intent==='COMMAND_HELP'){ this.reply(user,session,inserted.id,copy.help,'help'); return {accepted:true,userId:user.id,sessionId:session.id}; }
    if(c.safety==='high_risk'){ this.reply(user,session,inserted.id,copy.safety,'safety'); return {accepted:true,userId:user.id,sessionId:session.id}; }
    if(c.safety==='abuse'||c.safety==='off_topic'||c.intent==='OFF_TOPIC'||c.intent==='PROMPT_INJECTION'){ this.increment(session); this.reply(user,session,inserted.id,copy.redirect,'redirect'); return {accepted:true,userId:user.id,sessionId:session.id}; }
    if(c.intent==='COMMAND_RESET'){ this.db.updateSession(session.id,{state:'closed',last_activity_at:new Date().toISOString()}); this.reply(user,session,inserted.id,'Session reset. Your stable profile stays saved. Text me when you’re ready for a fresh plan.','reset'); return {accepted:true,userId:user.id,sessionId:session.id}; }
    // A name is always the first useful exchange for a new user.
    if(session.state==='awaiting_name' && c.intent==='PROVIDE_NAME') { const name=safeName(String(c.entities.name)); this.db.updateUserName(user.id,name); const pending=session.pending_action_json?JSON.parse(session.pending_action_json).deferred_user_text:''; this.db.updateSession(session.id,{state:'discovering',pending_action_json:null,inbound_turns:session.inbound_turns+1,last_activity_at:new Date().toISOString()}); session=this.db.getSession(session.id)!; this.reply(user,this.db.getSession(session.id)!,inserted.id,copy.nameSaved(name),'name'); if(pending && classify(pending,'discovering',true).intent!=='GREETING_OR_SMALLTALK'){ const pc=classify(pending,'discovering',true); const result=await this.discovery(user,session,inserted.id,pending,pc.intent); return {...result,userId:user.id,sessionId:session.id}; } return {accepted:true,userId:user.id,sessionId:session.id}; }
    if(session.state==='awaiting_name') { this.reply(user,session,inserted.id,'I didn’t catch a first name—what should I call you?','name_retry'); return {accepted:true,userId:user.id,sessionId:session.id}; }
    session=this.db.getSession(session.id)!;
    const protectedJoin=c.intent==='JOIN_PLAN' && !!session.active_recommendation_id;
    const maxTurns=user.turn_limit_override??this.opts.maxTurns;
    if(!protectedJoin && session.inbound_turns>=maxTurns) { if(!session.cutoff_sent_at){ this.db.updateSession(session.id,{state:'limited',cutoff_sent_at:new Date().toISOString()}); this.reply(user,session,inserted.id,copy.cutoff,'cutoff'); } return {accepted:true,userId:user.id,sessionId:session.id,limited:true}; }
    this.increment(session); session=this.db.getSession(session.id)!;
    if(c.intent==='JOIN_PLAN') return this.join(user,session,inserted.id);
    if(c.intent==='LEAVE_PLAN'){ if(session.active_recommendation_id) this.db.markExposure(session.id,session.active_recommendation_id,'rejected'); this.reply(user,session,inserted.id,'No problem—I left that plan untouched. Want another Stamford option?','leave'); return {accepted:true,userId:user.id,sessionId:session.id}; }
    if(c.intent==='APP_OR_CALENDAR'){ const link=this.appLink(user.id,session.id,'/for-you?view=calendar'); this.reply(user,session,inserted.id,`Your Mango week is here: ${link}`,'app'); return {accepted:true,userId:user.id,sessionId:session.id}; }
    if(c.intent==='MORE_OPTIONS' && this.db.exposures(session.id).length>=2){ const link=this.appLink(user.id,session.id,'/for-you?view=calendar'); this.reply(user,session,inserted.id,copy.appUpsell(link),'upsell'); this.db.updateSession(session.id,{state:'discovering'}); return {accepted:true,userId:user.id,sessionId:session.id,upsell:true}; }
    if(c.intent==='REJECT_RECOMMENDATION'&&session.active_recommendation_id) this.db.markExposure(session.id,session.active_recommendation_id,'rejected');
    return {...await this.discovery(user,session,inserted.id,text,c.intent),userId:user.id,sessionId:session.id};
  }
  private increment(s:SessionRow){ const turns=s.inbound_turns+1; this.db.updateSession(s.id,{inbound_turns:turns,last_activity_at:new Date().toISOString(),version:s.version+1}); }
  private async discovery(user:UserRow,session:SessionRow,inboundId:string,text:string,intent:Intent){ const ranked=rankOpportunities(this.db,user,session,text); const agent=await this.hermes.respond({user,session,message:text,intent,messageId:inboundId}); if(!ranked.length||!agent.opportunityId){this.reply(user,session,inboundId,agent.text||copy.noResult,'no_result');return {accepted:true};} const best=ranked.find(x=>x.opportunity.id===agent.opportunityId)||ranked[0]; let body=agent.action==='RECOMMEND'&&agent.text?agent.text:formatRecommendation(best,this.db.compatibleCount(user.id,best.opportunity.id)); if(!/\breply\s+join\b/i.test(body)){ const cta=' Reply JOIN and I’ll add it.'; body=`${body.trim().slice(0,600-cta.length)}${cta}`; } this.db.expose(user.id,session.id,best.opportunity.id,best.score,best.reasons,body); this.db.updateSession(session.id,{state:'discovering',recommendation_count:this.db.exposures(session.id).length,active_recommendation_id:best.opportunity.id,summary:`Recommended ${best.opportunity.title}; reasons ${best.reasons.join(',')}`}); this.reply(user,session,inboundId,body,'recommendation'); return {accepted:true,opportunityId:best.opportunity.id}; }
  private join(user:UserRow,session:SessionRow,inboundId:string){ const id=session.active_recommendation_id!; const o=this.db.getOpportunity(id); if(!o){this.reply(user,session,inboundId,'Which plan should I add? Reply with the event name.','join_ambiguous');return {accepted:true};} this.db.createJoin(user.id,id,session.id); this.db.updateSession(session.id,{state:'joined',pending_action_json:null}); const link=this.appLink(user.id,session.id,`/plans/${encodeURIComponent(id)}`); this.reply(user,session,inboundId,copy.joined(o.title,link),'joined'); return {accepted:true,joined:true,opportunityId:id}; }
}
