import Fastify, { type FastifyInstance } from 'fastify';
import { MangoDb } from './db.js';
import { AndroidHttpAdapter, AndroidLocalSimAdapter } from './adapter.js';
import { Orchestrator } from './orchestrator.js';
import { verifyAppToken } from './token.js';
import type { CanonicalInbound } from '@mango/contracts';
import { randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';

export interface AppRuntime { app:FastifyInstance; db:MangoDb; orchestrator:Orchestrator; simulator:AndroidLocalSimAdapter; drain:()=>Promise<number>; stopWorker:()=>void; }
function loadTurnLimitBypassPhones(path=process.env.PHONE_WHITELIST_PATH||'./data/phone-whitelist.json') {
  try {
    const parsed=JSON.parse(readFileSync(path,'utf8')) as {allowed?:unknown};
    if(!Array.isArray(parsed.allowed)) return [];
    return parsed.allowed.flatMap((entry:any)=>entry?.enabled===true && typeof entry.phone==='string'?[entry.phone]:[]);
  } catch { return []; }
}
export function buildApp(options:{db?:MangoDb; webhookSecret?:string; adminToken?:string; appBaseUrl?:string; linkSecret?:string; turnLimitBypassPhones?:string[]}={}):AppRuntime {
  const db=options.db||new MangoDb(process.env.DATABASE_URL||':memory:'); const simulator=new AndroidLocalSimAdapter(); const adapter=process.env.ANDROID_GATEWAY_BASE_URL?new AndroidHttpAdapter(process.env.ANDROID_GATEWAY_BASE_URL,process.env.ANDROID_GATEWAY_USERNAME||'',process.env.ANDROID_GATEWAY_PASSWORD||'',process.env.ANDROID_GATEWAY_DEVICE_ID||undefined,process.env.ANDROID_GATEWAY_SIM_NUMBER?Number(process.env.ANDROID_GATEWAY_SIM_NUMBER):undefined):simulator;
  const orchestrator=new Orchestrator(db,{maxTurns:Number(process.env.MAX_USER_TURNS||12),warningAt:Number(process.env.TURN_WARNING_AT||10),appBaseUrl:options.appBaseUrl||process.env.APP_DEEP_LINK_BASE_URL||'https://mango-io.vercel.app',linkSecret:options.linkSecret||process.env.DEEP_LINK_SIGNING_SECRET||'demo-deep-link-secret',turnLimitBypassPhones:options.turnLimitBypassPhones??loadTurnLimitBypassPhones()});
  const app=Fastify({logger:process.env.NODE_ENV==='test'?false:{redact:{paths:['req.url','req.headers.authorization','req.headers.x-mango-webhook-secret','req.headers.x-admin-token'],censor:'[Redacted]'}},bodyLimit:32768,genReqId:()=>randomUUID()}); const webhookSecret=options.webhookSecret??process.env.WEBHOOK_SHARED_SECRET??'demo-webhook-secret'; const adminToken=options.adminToken??process.env.ADMIN_TOKEN??'demo-admin-token';
  app.setErrorHandler((error,req,reply)=>{ req.log.error({err:error,request_id:req.id},'request failed'); reply.code((error as any).statusCode&&Number((error as any).statusCode)<500?Number((error as any).statusCode):500).send({error:'internal_error',message:'Mango hit a snag. Try again shortly.',request_id:req.id}); });
  // Tests get a deterministic drain hook; production remains fire-and-forget after durable enqueue.
  if(process.env.NODE_ENV==='test') app.addHook('onResponse',async()=>{await orchestrator.drain();});
  const auth=async(req:any,reply:any)=>{if(req.headers['x-mango-webhook-secret']!==webhookSecret) return reply.code(401).send({error:'unauthorized',request_id:req.id});};
  const cloudAuth=async(req:any,reply:any)=>{if(String(req.query?.token||'')!==webhookSecret) return reply.code(401).send({error:'unauthorized',request_id:req.id});};
  const admin=async(req:any,reply:any)=>{if(req.headers.authorization!==`Bearer ${adminToken}` && req.headers['x-admin-token']!==adminToken) return reply.code(401).send({error:'unauthorized',request_id:req.id});};
  app.get('/health',async()=>({ok:true,service:'mango-sms-api',database:'ok',hermes:process.env.HERMES_BASE_URL?'configured':'deterministic-simulator',gateway:process.env.ANDROID_GATEWAY_BASE_URL?'configured':'simulator',request_id:''}));
  app.post('/v1/channels/android/inbound',{preHandler:auth},async(req:any,reply)=>{ const p=req.body as Partial<CanonicalInbound>; if(!p||typeof p.provider_message_id!=='string'||typeof p.from!=='string'||typeof p.text!=='string'||p.text.length>1000) return reply.code(400).send({error:'invalid_payload',request_id:req.id}); const result=await orchestrator.enqueue({provider:p.provider||'android_local_sim',provider_message_id:p.provider_message_id,from:p.from,to:p.to,text:p.text,received_at:p.received_at||new Date().toISOString(),device_id:p.device_id}); return reply.code((result as any).duplicate?200:202).send({...result,request_id:req.id}); });
  app.post('/v1/channels/android/webhook',{preHandler:cloudAuth},async(req:any,reply)=>{ const body=req.body as any; const event=String(body?.event||''); const p=body?.payload||{}; if(event==='sms:received'||event==='mms:downloaded'){ const from=String(p.sender||p.phoneNumber||''); const text=String(event==='mms:downloaded'?(p.body||p.subject||''):p.message||''); const providerMessageId=String(p.messageId||body.id||''); if(!from||!text||!providerMessageId||text.length>1000) return reply.code(400).send({error:'invalid_payload',request_id:req.id}); const result=await orchestrator.enqueue({provider:event==='mms:downloaded'?'sms_gate_cloud_mms':'sms_gate_cloud',provider_message_id:providerMessageId,from,to:p.recipient?String(p.recipient):undefined,text,received_at:p.receivedAt||new Date().toISOString(),device_id:body.deviceId?String(body.deviceId):undefined}); return reply.code((result as any).duplicate?200:202).send({...result,request_id:req.id}); } if(event==='mms:received') return {accepted:true,waiting_for_download:true,event,request_id:req.id}; if(['sms:sent','sms:delivered','sms:failed'].includes(event)){ const status=event.slice(4) as 'sent'|'delivered'|'failed'; const providerId=String(p.messageId||''); if(providerId){ const job=db.db.prepare('SELECT id,status FROM outbound_jobs WHERE provider_id=?').get(providerId) as any; if(job){ const rank:any={queued:0,sent:1,delivered:2,failed:3}; if((rank[status]||0)>=rank[job.status]) db.db.prepare('UPDATE outbound_jobs SET status=?,error_code=? WHERE id=?').run(status,p.reason||null,job.id); } } return {accepted:true,event,request_id:req.id}; } return {accepted:true,ignored:true,event,request_id:req.id}; });
  app.post('/v1/channels/android/status',{preHandler:auth},async(req:any,reply)=>{ const p=req.body as any; if(!p?.provider_message_id||!['sent','delivered','failed'].includes(p.status)) return reply.code(400).send({error:'invalid_payload',request_id:req.id}); const job=db.db.prepare('SELECT id,status FROM outbound_jobs WHERE provider_id=?').get(p.provider_message_id) as any; if(job){ const rank:any={queued:0,sent:1,delivered:2,failed:3}; if((rank[p.status]||0)>=rank[job.status]) db.db.prepare('UPDATE outbound_jobs SET status=?,error_code=? WHERE id=?').run(p.status,p.error_code||null,job.id); } return {accepted:true,request_id:req.id}; });
  app.post('/v1/demo/simulate-inbound',{preHandler:admin},async(req:any,reply)=>{ const p=req.body as Partial<CanonicalInbound>; if(!p?.from||!p?.text||!p?.provider_message_id) return reply.code(400).send({error:'invalid_payload',request_id:req.id}); const result=await orchestrator.enqueue({provider:p.provider||'simulator',provider_message_id:p.provider_message_id,from:p.from,to:p.to,text:p.text,received_at:new Date().toISOString(),device_id:'deterministic-simulator'}); return reply.code((result as any).duplicate?200:202).send({...result,request_id:req.id}); });
  app.get('/v1/app/me',async(req:any,reply)=>{ const token=String(req.query?.token||''); const claims=verifyAppToken(token,options.linkSecret||process.env.DEEP_LINK_SIGNING_SECRET||'demo-deep-link-secret'); if(!claims) return reply.code(401).send({error:'link_expired',message:'That Mango link expired for privacy. Text Mango again for a fresh one.'}); const u=db.getUser(claims.user_id),s=db.getSession(claims.session_id); if(!u||!s||s.user_id!==u.id) return reply.code(404).send({error:'not_found'}); const facts=db.facts(u.id).map(f=>({key:f.key,value:JSON.parse(f.value_json),confidence:f.confidence})); return {profile:{displayName:u.display_name,userType:u.user_type,preferences:facts},joinedPlans:db.joined(u.id).map(j=>({...j,tags:JSON.parse(j.tags_json)})),recommendations:db.exposures(s.id).map(e=>{const o=db.getOpportunity(e.opportunity_id);return o?{id:o.id,title:o.title,venue:o.venue_name,neighborhood:o.neighborhood,score:e.score,reasons:JSON.parse(e.reason_codes_json)}:null}).filter(Boolean),matches:{safePreview:['Ava','Noah','Maya'],note:'Demo personas; meet in public and tell a friend.'},demo:true}; });
  app.get('/v1/admin/health',{preHandler:admin},async(req:any)=>({ok:true,request_id:req.id,database:'ok',hermes:process.env.HERMES_BASE_URL?'configured':'simulator',gateway:process.env.ANDROID_GATEWAY_BASE_URL?'configured':'simulator',inbound:db.inboundStats(),queue:db.queueStats(),lastInbound:db.db.prepare("SELECT created_at FROM messages WHERE direction='inbound' ORDER BY created_at DESC LIMIT 1").get(),lastOutbound:db.db.prepare("SELECT sent_at FROM outbound_jobs WHERE sent_at IS NOT NULL ORDER BY sent_at DESC LIMIT 1").get()}));
  app.get('/v1/admin/queue',{preHandler:admin},async(req:any)=>({request_id:req.id,inbound:db.inboundStats(),queue:db.queueStats()}));
  app.post('/v1/admin/users/:id/increase-limit',{preHandler:admin},async(req:any)=>{ const n=Number((req.body as any)?.limit||20); db.db.prepare('UPDATE users SET turn_limit_override=? WHERE id=?').run(Math.min(50,Math.max(10,n)),(req.params as any).id); return {updated:true,limit:n,request_id:req.id}; });
  app.post('/v1/admin/demo/reset',{preHandler:admin},async()=>{db.resetDemo();return {reset:true};});
  let running=true; let workerBusy=false; const flush=async()=>{if(!running)return; for(const j of db.readyJobs(Number(process.env.OUTBOUND_BATCH||20))){try{const result=await adapter.sendText({userId:j.user_id,encryptedDestination:j.destination,text:j.text,dedupeKey:j.dedupe_key}); db.markJobSent(j.id,result.providerMessageId);}catch(e:any){db.markJobFailed(j.id,e?.message||'gateway_error',!e?.permanent);}}}; const drain=()=>orchestrator.drain(Number(process.env.INBOUND_BATCH||100)); const worker=async()=>{if(!running||workerBusy)return; workerBusy=true; try { await drain(); await flush(); } finally { workerBusy=false; }}; const timer=setInterval(()=>void worker(),Number(process.env.OUTBOUND_POLL_MS||250)); timer.unref(); void worker();
  return {app,db,orchestrator,simulator,drain,stopWorker:()=>{running=false;clearInterval(timer);}};
}
